# Generated by Django 3.1 on 2020-09-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='nese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
