# Generated by Django 3.1 on 2020-09-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_nese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nese',
            name='name',
        ),
        migrations.AddField(
            model_name='nese',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examples.post'),
        ),
    ]
