# Generated by Django 3.1 on 2020-10-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_auto_20200927_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nese',
        ),
    ]
