# Generated by Django 3.1 on 2020-10-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_delete_nese'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
