# Generated by Django 3.1 on 2020-10-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0008_auto_20201006_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
